type OccupiedSeatsData = {
  [id : number]: {
    [time: string]: {
      [row: string]: {
        [seat: string]: boolean
      };
    };
  };
};

const occupiedSeatsData: OccupiedSeatsData = {
  1: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: true,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: true,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  2: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  3: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: true,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: true,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: true,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  4: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  5: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: true,
        seat5: true,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  6: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  7: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
  8: {
    "11:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "17:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
    "20:45": {
      row1: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
      },
      row2: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },
      row3: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
      },

      row4: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row5: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row6: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row7: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
      row8: {
        seat1: false,
        seat2: false,
        seat3: false,
        seat4: false,
        seat5: false,
        seat6: false,
        seat7: false,
        seat8: false,
        seat9: false,
        seat10: false,
      },
    },
  },
};
export default occupiedSeatsData;
